### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by sutty550e** [lurume84/bling-desktop#1]
Downloaded the 69mb zip, extracted, as you explained on the Blink forum, and ran the .exe on my Windows 10 PC. I get error "Failed to create manger, Error:0x803E0105"

Standard Windows 10 laptop, with no known issues. If you need more info about the PC or Windows version, please let me know. I'm not familiar with how to report on GitHub, so I hope this is okay.

![error](https://user-images.githubusercontent.com/23123387/52907195-09871480-3254-11e9-9e75-71921b8818c8.PNG)

**Comment by lurume84** [comment]
I have generated a new release that allows to continue with this problem but no notifications will be available. This will not be a huge problem right now but when movement notifications are ready it will be important to get this working. 

First check if you have Notifications enabled in "Notifications & action settings". If so, reboot your computer and try again. In case this does not solve it install last Service Pack if available. Let's see if this solves the problem. In the mean time you can work with the new release.

**Comment by sutty550e** [comment]
The above release did resolve this issue, providing a warning with regard to notifications.
