### ISSUE TITLE
Bling.exe - System Error 

### ISSUE THREAD

**Issue by saiber77** [lurume84/bling-desktop#10]
The program can't start because api-ms-win-core-winrt-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 

Windows 7 Professional x64
Core-i7 3770k
16GB RAM

**Comment by lurume84** [comment]
For Windows 7 support you need to install visual studio redistributables from https://support.microsoft.com/es-es/help/2977003/the-latest-supported-visual-c-downloads

Direct link:
https://aka.ms/vs/16/release/vc_redist.x86.exe

I will add this installer in next release so we officially support Windows 7.

**Comment by saiber77** [comment]
Thanks, still resisting Windows 10 for now... lol.

**Comment by saiber77** [comment]
I installed the redistributable package and the problem remains?

**Comment by lurume84** [comment]
Yes, you may need to install following KB to have the Universal CRT. If this does not solve the problem I will have to investigate it more in-depth.

https://www.microsoft.com/en-US/download/details.aspx?id=49077

**Comment by saiber77** [comment]
Thanks for the reply, didn't seem to resolve it. Also your link is for the 32bit version. Here's the 64bit link for anyone else that may be helped by this resolution.

https://www.microsoft.com/en-us/download/details.aspx?id=49093

**Comment by saiber77** [comment]
![Bling exe](https://user-images.githubusercontent.com/9895596/59657805-a8feda00-9156-11e9-83bf-64abc2d359e1.jpg)

**Comment by saiber77** [comment]
Any ideas? Still a problem...

**Comment by lurume84** [comment]
Sorry I have been trying to make It work but some of the libraries I link to are from Windows 10. I Will have to generate a separate compilation for Windows 7 users. 

Let me check this alternative and will post tomorrow.

**Comment by saiber77** [comment]
No worries lurume84, I just hadn't heard anything in awhile so thought I'd ask. Absolutely no need to apologize, I understand how busy life can be, especially if you are also feeling beholden to a mass of people counting on something you made to work. 

I know Windows 7 official support will be over Jan. 2020 but I and other diehard W7 users will continue to hold out until it's absolutely necessary to switch to 10. I am not a fan of the W10 OS although I am a computer technician so I work on it constantly, all the more reason for me not to like it, lol.

**Comment by saiber77** [comment]
Which libraries are you linking to from W10? I am no programmer but I was curious. Are you using a VM to test it or a physical computer?

**Comment by lurume84** [comment]
Gotcha! As suspected problem was related to using new Windows Notifications system available since Windows 8.1. I have generated a separate compilation for Windows 7 without these notifications. This is not a big deal since it is only used to notify of new desktop or viewer upgrades.

In practice, when you see a new viewer release in https://github.com/lurume84/bling-viewer you will have to close the desktop application, go to documents/BlingW7.exe/Html and delete viewer folder. Once you open the desktop again, it will download the last release automatically.

Hope this works for you, I also make software for W7 OS so no worries in future support.
