### ISSUE TITLE
Default download/save directories and default naming

### ISSUE THREAD

**Issue by cabersc** [lurume84/bling-desktop#11]
Just found this from the Blink community where I was complaining about lack of knowing if I was on battery or line power.  Great app, and appreciation for the work you've done!

I was wondering about a couple of features, mainly around the ability to specify a default save directory for manually downloaded videos as well as those automatically synced by the app.  I use multiple machines in my home, and would love to be able to have a common download location (on my NAS) for the synced videos and Download videos.  This could be something like:

DefaultSyncPath=N:\BlingVideoSync
DefaultDownloadPath=%userprofile%\Videos\BlingVideos

The other thing that would be nice is if there's a way to extract the date/time of the recording, to specify by default during the download process, as there seems to be no logic to the suggested download file names, so if I want to download a file and give it any specific date names, I need to either find it in the Download\Videos folder, or look up the date/time on the Blink App on my phone, since those details are not shown in the BlingDesktop.

Depending on feasibility, it'd be nice to be able to have a formatting of the default filenames, based on what can be extracted from the video metadata:

%cn = Camera Name
%YYYY = year
%mm = month
%dd = day 
%h = hour (24 hour clock maybe?)
%m = minute

Something like this would allow the flexibility to automatically name files in a flexible format that could be fed to other actions.

Also, is there a way to be able to allow deletion of videos from BlingDesktop, or does that have to happen via the mobile app or by auto-expiring?

Thanks!

**Comment by lurume84** [comment]
Thanks! Some of the things you request are already working but I did not expose this information in the readme.md file. I have updated it so if you open the project page again you should see new information.

Basically, I explain how Blink.ini works inside %userprofile%/Documents/Bling.exe folder. For downloading videos to a particular output you need to change [SyncVideo] section so Output setting points to it. This solves your problem for automatically synced videos. For videos manually downloaded it's easy, I will include a new section in ini file to configure this for next release.

The name for each video is its epoch timestamp. This information directly comes from Blink servers. What you can do is set UseLocalTime setting to true so videos will be renamed to your computer's local timezone following this expression %Y-%m-%dT%H:%M:%S+00:00.

Video deletion has been requested by many users. I will include it hopefully in next viewer release but do not expect a bulk deletion functionality as could induce some unrecoverable "human errors".

**Comment by cabersc** [comment]
Awesome.  Thank you for the details on blink.ini as that certainly helps keep everything from multiple systems in a common location, and addresses most of my questions.
