### ISSUE TITLE
add option to change temperature to Celsius.

### ISSUE THREAD

**Issue by vampywiz17** [lurume84/bling-desktop#13]
Hello @lurume84 ,

It would be great, that possible to change temperature to Celsius.

**Comment by lurume84** [comment]
Also included in today's release. I could not gather this info from blink servers as seems they have partially implemented it. Temp units are stored in mobile app so no way to know which one is used. I have added both until they solve it.

**Comment by vampywiz17** [comment]
Great, thanks!
