### ISSUE TITLE
Disable unnecessary things on live view.

### ISSUE THREAD

**Issue by vampywiz17** [lurume84/bling-desktop#15]
Hello @lurume84 !

I found a unnecessary thing in live view. I don't know that is possible to disable it, or not.

Camera number

next to camera name the camera number is seeable. It possible that is need some user, so it would be great that is possible o disable it with .ini file.

**Comment by lurume84** [comment]
Ok I have released a new version with more info for each camera and also a dashboard. Issues related with UI should be bentered in bling-viewer project so I can relate them when releasing. Bling is composed by two projects, the container and the content. Hope this release helps you!

**Comment by vampywiz17** [comment]
The new option is great!!

That's what I was thinking
