### ISSUE TITLE
Bling Thumbnail Sync

### ISSUE THREAD

**Issue by shoey79** [lurume84/bling-desktop#19]
Hello again,

All appears to be working fine since the last release, except the generation of updated thumbnails via the "SyncThumbnail" part of the ini.

I can manually update the image but it no longer updates each hour (default 3600) nor stores them in the default folder.

"C:\Users\shoey79\Documents\Bling.exe\Download\Thumbnails" has no images in it.

[SyncThumbnail]
Enabled=true
Interval=3600
Sleep=5
Retries=10

Just thought I'd let you know :-)

Thanks again for your efforts!

**Comment by lurume84** [comment]
It should be solved now, thanks for the feedback!

**Comment by shoey79** [comment]
Thanks again, resolved!
