### ISSUE TITLE
XT2 liveview problem

### ISSUE THREAD

**Issue by mduzgun** [lurume84/bling-desktop#26]
I use XT2 camera, so I get stream url as "immis://35.157.134.172:443/uFF7gXXXXXXXXXXX__IMDS_825XXXXXX?client_id=XXX". 
Is there any way use this url? 
I don't find any info for "immis".
Could you help me anyone?

**Comment by lurume84** [comment]
XT2 liveview is not supported at this moment I'm sorry. Blink made some modifications to the RTSP protocol for the two-way communication I think. I do not have XT2 cameras, just XT, so I cannot adapt the current implementation for them. I don't even know if it is achievable until I put my hands on to be honest

**Comment by mduzgun** [comment]
I used another blink camera and I get stream url as "rtsps://lv1-app-u012.immedia-semi.com:443/XXXXXZqZs9zkJKzu__IMDS_13409XXXX?client_id=XX&blinkRTSP=true".

I tried bling-desktop and bling-viewer, but liveview is not working.

Is this stream url format proper for bling-desktop and bling viewer?

**Comment by lurume84** [comment]
All cameras except XT2 should work with bling-desktop. The other application, bling-viewer, has nothing to do with the live-view as this is completely handled by the desktop app. An url as the form you put should be correctly streamed by this app, check what ffmpeg log says at

%userprofile%\Documents\Bling.exe\Download\Videos\year\month\day\LiveView_XXX\

**Comment by mduzgun** [comment]
Thanks, I tried again, I wait a some time then it worked. 
Then, I directly tested ffmpeg command that I saw in log file in terminal, I got error. 
Do you have any idea for error?


"ffmpeg -report -i "rtsps://lv1-app-u012.immedia-semi.com:443/rTCaVmydXXXX__IMDS_1340XXXXX?client_id=XX&blinkRTSP=true" -c copy -vcodec copy -g 30 -hls_time 1 out.m3u8 -vcodec copy video2.mp4
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Splitting the commandline.
Reading option '-report' ... matched as option 'report' (generate a report) with argument '1'.
Reading option '-i' ... matched as input url with argument 'rtsps://lv1-app-u012.immedia-semi.com:443/rTCaVmydXXXX__IMDS_1340XXXXX?client_id=XX&blinkRTSP=true'.
Reading option '-c' ... matched as option 'c' (codec name) with argument 'copy'.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
Reading option '-g' ... matched as AVOption 'g' with argument '30'.
Reading option '-hls_time' ... matched as AVOption 'hls_time' with argument '1'.
Reading option 'out.m3u8' ... matched as output url.
Reading option '-vcodec' ... matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
Reading option 'video2.mp4' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option report (generate a report) with argument 1.
Successfully parsed a group of options.
Parsing a group of options: input url rtsps://lv1-app-u012.immedia-semi.com:443/rTCaVmydXXXX__IMDS_1340XXXXX?client_id=XX&blinkRTSP=true.
Successfully parsed a group of options.
Opening an input file: rtsps://lv1-app-u012.immedia-semi.com:443/rTCaVmydXXXX__IMDS_1340XXXXX?client_id=XX&blinkRTSP=true.
[tls @ 000001869ac26d00] No default whitelist set
[tcp @ 000001869ac26fc0] No default whitelist set
[tcp @ 000001869ac26fc0] Original list of addresses:
[tcp @ 000001869ac26fc0] Address 35.167.201.133 port 443
[tcp @ 000001869ac26fc0] Address 54.148.144.193 port 443
[tcp @ 000001869ac26fc0] Interleaved list of addresses:
[tcp @ 000001869ac26fc0] Address 35.167.201.133 port 443
[tcp @ 000001869ac26fc0] Address 54.148.144.193 port 443
[tcp @ 000001869ac26fc0] Starting connection attempt to 35.167.201.133 port 443
[tcp @ 000001869ac26fc0] Successfully connected to 35.167.201.133 port 443
[rtsp @ 000001869ac23dc0] CSeq 2 expected, 1 received.
[rtsp @ 000001869ac23dc0] SDP:
v=0

o=- 0 0 IN IP4 127.0.0.1

s=name

c=IN IP4 127.0.0.1

t=0 0

a=tool:immedia_isi108 0.0.1

a=control:*

m=video 5002 RTP/AVP 33

a=rtpmap:33 MP2T/90000

a=control:trackID=1

a=range:npt=now-

rtsps://lv1-app-u012.immedia-semi.com:443/rTCaVmydXXXX__IMDS_1340XXXXX?client_id=XX&blinkRTSP=true: Invalid data found when processing input"

**Comment by lurume84** [comment]
Sorry no idea. I'm currently working on the multiplatform version. If I succeed on executing liveview for Linux/Mac I will answer here.
