### ISSUE TITLE
version 0.1.19 - get "Unsupported 16-Bit Application" error

### ISSUE THREAD

**Issue by petunia101** [lurume84/bling-desktop#28]
Hello again, 
I tried installing the version 19 update and was having troubles with it hanging up again, so...

1) I uninstalled the application
2) also deleted the Bing.exe folder under Documents
3) downloaded and ran the BlingSetup.exe file
4) ran Bling.exe under AppData/Local/Bling Desktop
5) starts loading and tells me version 19 upgrade is available and do I want to install?  I click yes.
6) then I get error message about "Unsupported 16 Bit Application" (snapshot of error message attached)
7) when i click ok on error message it closes but the white window stays - it's hung up
8) there is no crash report and the Bling.log file is 0kb and empty.....

I tried this twice and both times got the 16 Bit Application error...
![Unsupported 16-Bit Application error](https://user-images.githubusercontent.com/64242783/80270716-85ff5980-8688-11ea-8bf4-ac1cf2b38a47.JPG)

**Comment by lurume84** [comment]
The desktop downloaded seems to be corrupted. I have released 0.1.20 solving the problem with videos. Open the app again and let's see if it asks for downloading 0.1.20. If so, click yes and in case it gives the same problem go to /Bling.exe/Download/Versions/Desktop/ and delete everything inside. Then repeat the steps again. You can also manually download latest desktop version and install it.

This new version also allows to disable automatic desktop and viewer upgrades through Bling.ini with

[UpgradeDesktop]
Enabled=false
[UpgradeViewer]
Enabled=false

Just in case you need to have a stable release because I will be improving the application these days and may be a bit frustrating having issues in case you really need to get the videos.

**Comment by petunia101** [comment]
Hi,

Sorry, but I don’t quite understand how this github site works.... How to navigate it.... how would I find the desktop version to manually install it?

And thanks for the tips about disabling the automatic upgrades.  I will definitely do that once I get it working :)

Janette

On Apr 25, 2020, at 12:50 PM, Luis Ruiz <notifications@github.com> wrote:

﻿

The desktop downloaded seems to be corrupted. I have released 0.1.20 solving the problem with videos. Open the app again and let's see if it asks for downloading 0.1.20. If so, click yes and in case it gives the same problem go to /Bling.exe/Download/Versions/Desktop/ and delete everything inside. Then repeat the steps again. You can also manually download latest desktop version and install it.

This new version also allows to disable automatic desktop and viewer upgrades through Bling.ini with

[UpgradeDesktop]
Enabled=false
[UpgradeViewer]
Enabled=false

Just in case you need to have a stable release because I will be improving the application these days and may be a bit frustrating having issues in case you really need to get the videos.

**Comment by lurume84** [comment]
Did the 0.1.20 automatically download correctly? Otherwise close the application and download from here:

https://github.com/lurume84/bling-desktop/releases/download/0.1.20/BlingSetup.exe

**Comment by petunia101** [comment]
Hello,
Sorry for the delay.
When I just restarted the program it did ask about did I want to upgrade to version 20.  I said yes, but then it just got hung up.

So I uninstalled and deleted the Bling.exe folder and redid the setup.  First it didn’t seem like it worked because I got an error message about blink already running or something like that.  I stopped the install.  But I must have double clicked or something and the the first install completed.

The viewer is working! The order of the videos is still strange though just FYI.  The good news is it is downloading the videos now.

Thanks for your help again!
Janette

On Apr 25, 2020, at 1:50 PM, Luis Ruiz <notifications@github.com> wrote:

﻿

Did the 0.1.20 automatically download correctly? Otherwise close the application and download from here:

https://github.com/lurume84/bling-desktop/releases/download/0.1.20/BlingSetup.exe

**Comment by petunia101** [comment]
Just FYI in case you are not aware....Blink is sending out emails saying current automation scripts will no longer work....
Email below....
Janette


Dear Blink Customer,

You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11<x-apple-data-detectors://0>.

We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com<mailto:info@blinkforhome.com> for consideration.

Thank you,



On Apr 25, 2020, at 1:50 PM, Luis Ruiz <notifications@github.com> wrote:

﻿

Did the 0.1.20 automatically download correctly? Otherwise close the application and download from here:

https://github.com/lurume84/bling-desktop/releases/download/0.1.20/BlingSetup.exe

**Comment by lurume84** [comment]
Thanks for the info! Another user posted it in issue #31  , please follow the thread there. Basically I have released a new version for both desktop and viewer that should solve the problem. Let's hope this upgrade is less dramatic than the other one!
