### ISSUE TITLE
Great App - had signin from Ohio?

### ISSUE THREAD

**Issue by Muttley33** [lurume84/bling-desktop#30]
Really nice app - worked like a dream. After I signed in I got a message from Blink:- 

A new device has been used to sign into your Blink account.

IP Address: 18.217.34.195
Location: Columbus, Ohio, United States

That is expected right?

Thanks again

**Comment by lurume84** [comment]
Thanks! Another user in the Blink forums commented the same. I imagine Blink has mitigated the lack of 2 factor authentication by emailing when a new ip is detected. Check if this IP corresponds to your ISP or open a cmd and execute:

tracert prod.immedia-semi.com

Check if that ip is in the list. We normally connect to Blink using our smartphones and 4G, it's expected to have this false positive when we connect with a computer that has a different MAC.

**Comment by lurume84** [comment]
Additional information:

"nslookup 18.217.34.195" gives 

ec2-18-217-34-195.us-east-2.compute.amazonaws.com

Blink servers are located in Amazon cloud since their acquisition.

**Comment by Muttley33** [comment]
Ok thanks - definitely not my ISP - I am UK based. Thanks for the prompt response
