### ISSUE TITLE
No account id: {"authtoken" ... also received email "Notice: Disabling Unauthorized 3rd Party Automation Scripts"... related?

### ISSUE THREAD

**Issue by DangRock** [lurume84/bling-desktop#31]
Hello!  I've been using your app to take snapshots of my pool construction for a couple weeks now.  I figured I'd start my own thread for questions rather than hijack the other topic again.  I received an email from Blink support today:  

Title: Notice: Disabling Unauthorized 3rd Party Automation Scripts
Body:  

> 
> Dear Blink Customer,
> 
> You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. 
> 
> We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. 
> 
> Thank you, 
> 
> Team Blink 

Is the error I get when I log in about no account id/authtoken related to this?  The error is: 

> No account id: {"authtoken":{"authtoken":redacted, "message":"auth"}, "networks":{redacted, {"name":"Castillo de Cerezo","onboarded":true}},"region":{"prod":"United States"},"account":{"id":0}}

Thoughts?  Thanks!  Rocky

**Comment by lurume84** [comment]
Thanks for the info! I also received it.

I have just released a new desktop and viewer version that uses the new login system. We should be covered for 5/11 but wanted to release it ASAP to see any error before the day comes.

This version will potentially solve your account id issue. Bad news are you become a betatester of it.

**Comment by DangRock** [comment]
Great, thanks!  It's working great so far.  I did have a couple quirky things where after I installed 0.1.21 it told me I need to upgrade to 0.1.18, and clicking the pop-up (bar at top) didn't do anything, but it did get rid of the warning and I haven't seen it since. 

The first time I logged in, it directed me to wait for a code from Blink and enter it, but I never got the code.  I cancelled, and then re-opened and it auto-logged in for me and worked for about half a day.  Then my log-in must have expired and it logged me out.  The next time I logged in, this morning, it took me back to the code screen, but I did get a code this time and entered it and everything is good to go right now.    

I'll let you know if it does anything weird.  I do know I have to run 0.1.16 viewer. If I upgrade to the latest viewer it gives me Java errors.  I read somewhere you have flags for the .ini that stop it from auto-updating.  What should I add so it doesn't try to upgrade the viewer automatically again?

**Comment by petunia101** [comment]
Hello,
Just wanted to offer feedback that the new version is working for me as well.  Initially after running BlingSetup.exe and then trying to run the app, I got the get "Unsupported 16-Bit Application" error that I had posted as an issue previously.  I clicked ok and then it was just a white screen.  <-- because that seemed familiar to what I had happen to me previously when I was having errors, I just decided to close the app, and then retry the app.  This time is opened normally and took me to login screen,  I entered user name and login and then it gave me the note about having to enter code that was sent to my email,  Checked my email and entered the code and it worked.  It is downloading videos as usual.  

Thank you very much for the update!
Janette

**Comment by petunia101** [comment]
DangRock,
I saw your question about how to prevent automatic updates.....
This is what I was told before:

create a Bling.ini file in %userprofile%/Documents/Bling.exe folder with

[UpgradeDesktop]
Enabled=false

[UpgradeViewer]
Enabled=false

------------------
the above stops both the viewer and desktop app from updating.  I hope it helps you...
Janette

p.s. You may know this already but if you go under Issues and then "filter" on the "Closed" issues you can read through past problems people have had and the fixes.  I am in no way a computer person but reading through past fixes helps me at least get some ideas of what I can try.  Now as to whether I am successful or not - that's a whole different question :)

**Comment by DangRock** [comment]
Hey lurume84... just wanted to give an update on my use of your app... working great for my timelapse photos.  There is one quirk, though, that you may want to think about.  

I leave the app running all the time so it takes pictures regularly.  It "expires" after 24-36 hours or so and requires me to close and re-open and authenticate.  As noted earlier, now... when it authenticates, it pops up that 2nd dialog for the code that is emailed.  What I've found is that it doesn't matter if I enter the code or not... the app will expire after 24-36 hours either way.  I can bypass waiting for and entering the code by simply closing the Bling app from the task bar and then re-opening.  It won't ask me to log in this time, effectively bypassing the need to enter the emailed code. 

SO... my thought is maybe the app isn't actually using the code that is emailed, as I would expect, if it were correctly authenticated, it would last for more than a day or so.  

Just some thoughts, thanks!

**Comment by lurume84** [comment]
Hi, thanks for the feedback. I have released .19 version that enables reauth during the login process. It is just a test because I have no API information but seems that could be related.

Please confirm your app upgrades to .19 and check if after 24h still works. (remove token.json file inside %userprofile%/Documents/Bling.exe/Html/viewer/data and login in the app again so we send reauth=false this time.)

Thanks!
