### ISSUE TITLE
no 64 bit support  ?

### ISSUE THREAD

**Issue by marlur** [lurume84/bling-desktop#33]
I am not sure if someone else has the problem but i cannot install the app.
It complaints that it is not 64 bit compatible.

**Comment by lurume84** [comment]
It is a 32 bits application but will work in any Windows 64 bits. Which version is your Windows? Please put the exact message you get here.

**Comment by marlur** [comment]
Hi, i apologize.
I now tried to install it a second time to write down the exact error.
But this time it just installed and startet up the application, it works now.
I don't know why the error message occured at the first trial.

**Comment by lurume84** [comment]
No worries! It may be a corruption during download.
