### ISSUE TITLE
App immediately closes

### ISSUE THREAD

**Issue by yeahfab** [lurume84/bling-desktop#36]
I had been running the program for over a week and suddenly today me laptop froze.  when i tried to run the program after turning my laptop back on the program wouldn't run.  i get a window that reads "bling has stopped working" but it closes to quickly to do anything.  i have uninstalled and reinstalled and nothing changes

**Comment by lurume84** [comment]
Remove folder Bling.exe inside Documents and install everything fresh again. It may be a problem of compatibility between viewer and desktop.
