### ISSUE TITLE
Stops downloading after 1 day

### ISSUE THREAD

**Issue by cyturralde** [lurume84/bling-desktop#38]
I can't pin point an exact time but after about 24-36 hours it stops downloading from Blink. Is there something I can do to prevent this from happen?

Also is there a way to change the name of the files?

**Comment by lurume84** [comment]
I have released a new version, check if you have viewer version .19 at the botton left of the app after opening it. Remove token.json file inside %userprofile%/Documents/Bling.exe/Html/viewer/data and login in the app again.

I am not sure if this will solve the problem but I saw I was sending reauth=true during login process so let's see if this solves it.

**Comment by cyturralde** [comment]
Thanks for responding :). I am showing 1.16 viewer version and 1.21.0 desktop.

**Comment by cyturralde** [comment]
That is after updating to the latest version. And I deleted that token file.

**Comment by lurume84** [comment]
Viewer must be  v0.1.19. If this is not the case please remove %userprofile%/Documents/Bling.exe/Html/viewer folder. Also delete any compressed file inside %userprofile%/Documents/Bling.exe/Downloads/Viewer/

Open the app and should update automatically to 0.1.19

**Comment by cyturralde** [comment]
Interesting outcome. So I deleted those files. On opening the app still says the viewer is .1.16 but the compressed file in %userprofile%/Documents/Bling.exe/Downloads/Viewer/ is labeled as .1.19

**Comment by cyturralde** [comment]
So it still stops, if I check the log it looks like when it stops I just get a bunch of lines that look like this:

[2020-07-03 14:27:42.029] [BlingLog] [info] HTTP GET 401 rest-u020.immedia-semi.com:443/api/v1/accounts/*****/media/changed?since=2020-07-02T23:04:39+00:00&page=1

I starred out that number because I Wasn't sure if it was unique to me or not.

**Comment by cabersc** [comment]
For me, even after deleting the html/viewer directory and replacing it with 0.1.19 download, my viewer version still shows as 0.1.16.

![Bling Versions](https://user-images.githubusercontent.com/52379868/87098315-99907a00-c20c-11ea-9cec-b861587b29e2.JPG)

**Comment by DangRock** [comment]
Same here... totally deleted entire install location and downloads... installed latest exe and have 0.1.16/0.1.21.0, like in your picture.  Also, still get the daily expiration, regardless of if I do the post-login validation code.

**Comment by lurume84** [comment]
I'm sorry there was a typo in 0.1.19 and displayed 0.1.16 instead because it's a manual change I do every release. i have generated 0.1.20 and should show up correctly.

I will take a look into other projects to see how they deal with disconnections.

**Comment by Ananovah** [comment]
I'm a new user and started with 0.1.20 and I too am having this issue. It seems after 24 hours I have to re-authenticate.
