### ISSUE TITLE
Videos were downloading as of July 6th, 2020 - but no longer downloading

### ISSUE THREAD

**Issue by petunia101** [lurume84/bling-desktop#39]
Hello,

I am not sure what is going on.... the program was working well - the 2FA was working - I would get email with code and after entering the code, I could view the videos and they also would start downloading.

All was well until July 6th, when for some reason the downloads stopped...

I ended up uninstalling (from the Bling Desktop folder under the users/me/Appdata/local folder) the program.  I also renamed the Bling.exe folder so that it would create a new folder when I ran setup.  I downloaded the latest BlingSetup file from GitHub and ran it.

It seems to have installed well, and it created a new Bling.exe folder.

I can open the Bling Desktop file.  At bottom left hand corner of Blink Viewer window it says Viewer version 1.16 and Desktop version 1.21.

No videos download though.

I am hoping you may know what is going on......

Thanks,
Janette

**Comment by cabersc** [comment]
I'm seeing the same thing.  My viewer version is showing 0.1.16 with a 0.1.21.0 desktop version, despite uninstalling and removing Bling and starting a new directory in my Documents folder.  Nothing seems to be downloading.  Logfile shows video sync every 60 seconds to the default download videos directory, but nothing seems to ever actually download.
[Bling.log](https://github.com/lurume84/bling-desktop/files/4899862/Bling.log)

**Comment by lurume84** [comment]
I'm sorry there was a typo in 0.1.19 and displayed 0.1.16 instead because it's a manual change I do every release. i have generated 0.1.20 and should show up correctly.

I will take a look into other projects to see how they deal with disconnections.

**Comment by JohnTombs** [comment]
Please see my note in #41.

**Comment by jdunevant** [comment]
Like-wise, I haven't had any captured video files download since the first week of July.  I've reinstalled, added & tweaked the ini but to no avail.  Interestingly it is saving LiveViews, which it didnt previously.

**Comment by martinvandenhurk** [comment]
I'm having a similar problem. Login with 2FA works fine but downloading the video's fails. I tried a clean new installation but it didnot help. I think we need Lurume84, are you on holiday?

**Comment by lurume84** [comment]
Sorry people I was working on other projects. I hope tomorrow I can invest some time on this!

**Comment by lurume84** [comment]
I think I found what was happening. Something at Blink servers has changed (maybe http has been completely deprecated). I have moved to a new https client so querys no longer fails.

I have not tested it since I have no clips on my system (my dogs ate cables from the cameras and they are offline from a long time ago). Please confirm everything works with release I'm about to upload right now, thanks!

**Comment by jdunevant** [comment]
That seems to have resolved it for me.  Thanks!

**Comment by cabersc** [comment]
Agreed.  Seems to be downloading all the videos it'd not been able to before.  Thanks for the update, Luis!

**Comment by JohnTombs** [comment]
0.1.23 now working for me also. Many thanks!
