### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sutty550e** [lurume84/bling-desktop#4]
Hello Lurume84

You suggested on the Blink forum that feature requests be submitted as an issue, so that's what I'm doing. If this is an incorrect procedure, please let me know. Anyway, here goes:

Please can we have a button under each camera thumbnail view, to take a new snapshot on demand. I note that others have asked for a timed option, once per hour, for example, and then saved. That would be a cool option, though not so useful to me, but I thought I'd mention it on their behalf.

Thanks

Sutty

**Comment by lurume84** [comment]
Of course. This last release has prepared the field for automatic thumbnail execution, your request is more suited to the bling-viewer itself. This weekend I will generate a new version that contains your request alongside a protection for the deleted videos problems. (let's cross fingers Blink REST allows us to execute this without problems)

**Comment by lurume84** [comment]
I have added this feature. Snapshot is requested to the camera updating also temperature and update time. It will be available in next release as I am trying to reduce the number of releases by including more functionality. In case you need it ASAP you just need to download last bling-viewer and paste its contents inside %appdata%/Bling Desktop/Html/viewer.
