### ISSUE TITLE
Wish List: Option to vary size of thumbnails.

### ISSUE THREAD

**Issue by PeteCress** [lurume84/bling-desktop#5]
As they are, thumbnails seem too small to be of any use, and might as well be eliminated to give a more compact list.

But what if there were an option that let the user set thumbnail size?

Then, if they could be large enough, they might supply some of the functionality of automagically-scheduled repeating snapshots by allowing the user to get some idea of what's happening just by quickly eyeballing the list of clips.

Sounds like a good bit of work and the scheduled snapshots are really where it's at - but maybe an idea worth kicking around.

**Comment by lurume84** [comment]
I agree, I am working in a new activity module. We will leave the current one as an Event history and the new activity will work as the Ring one.

https://www.youtube.com/watch?v=Zrqt44zwerg&feature=youtu.be&t=22
