### ISSUE TITLE
Cant login - An app update is required 

### ISSUE THREAD

**Issue by SeanDean02** [lurume84/bling-desktop#51]
Was logged in yesterday with no issues but tried to log in today and upon loading the app it says "Unortherised access", when I then put in the login details it says "An app update is required"

Any ideas why this could be and how I can fix it?

Cheers,
Sean

**Comment by shoey79** [comment]
Same here, suspect Blink have changed things yet again...so our friendly Bling developer will no doubt be looking in to it.

**Comment by SeanDean02** [comment]
@shoey79  Are you still having this issue like me or has it sorted itself out on your end?

**Comment by jdunevant** [comment]
I'm still experiencing the issue, too.

**Comment by shoey79** [comment]
> @shoey79 Are you still having this issue like me or has it sorted itself out on your end?

Negative, computer still says No.

**Comment by mmir** [comment]
Same problem, "An app update is required"

**Comment by lurume84** [comment]
I have released 0.1.24, hope it solves the problems. 

Sorry for the delay answering!!

**Comment by shoey79** [comment]
Thank you very much again! Yes it is working again! 👍

**Comment by SeanDean02** [comment]
@lurume84  Cheers it's all working now.
Thank you for getting this up and running again for us :)

**Comment by shoey79** [comment]
@lurume84 , Hello again, whilst the app is loading OK now, I can't seem to get it to download videos again, it doesn't seem to start. Any ideas?

**Comment by jdunevant** [comment]
Same here.  I have stopped and re-started the app a few times but no downloads have occurred.

**Comment by lurume84** [comment]
Yes it's because I forgot to do a change, tomorrow I Will apply the change

**Comment by shoey79** [comment]
@lurume84  Thanks again.

**Comment by SeanDean02** [comment]
@lurume84 any news on the update for the video downloading aspect of the app, please?

**Comment by lurume84** [comment]
released 0.1.26, let's see if it works!

**Comment by shoey79** [comment]
Yes! Lovely thank you again!!

**Comment by jdunevant** [comment]
I'm still experiencing issues.  Now using viewer 0.1.26,, desktop 0.1.23.0.

1. Cannot view any videos via bling but can via Blink app
2. No backups created for ones 
3. Live view did not display anything on the bling app but did back up the video of the live view

**Comment by lurume84** [comment]
Please delete token.json inside bling.exe/Html/viewer/Data and try again

**Comment by jdunevant** [comment]
Thanks, Luis.  As usual, that did the trick.  Thanks for your ongoing support.
