### ISSUE TITLE
Wish List: Make version upgrades easier

### ISSUE THREAD

**Issue by PeteCress** [lurume84/bling-desktop#7]
- Add code to 'About' option so user can verify
  which version they are running

- Upgrade .msi to auto-uninstall old version before
  installing new version.

**Comment by lurume84** [comment]
First one done, your Desktop should notify there is a new update. 

I will investigate second request.

**Comment by PeteCress** [comment]
I am trying to write a .BAT file to automate the new-version-install process:

_**`:* PURPOSE: To force Bling to update itself to the latest-and-greatest
:*          Viewer code

TASKKILL /IM Bling.exe

C:
CD %appdata%\Roaming\Bling Desktop\Html\viewer
DEL *.*

CD %userprofile%/Documents/Bling.exe/Download/Versions
DEL *.*

C:\Users\Kolon\AppData\Roaming\"Bling Desktop"\bling.exe

PAUSE`**_

Seems to work... sort of (trips on a couple Deletes if not run in Admin mode), but 
the last line - where we want to restart Bling does not seem to work.

Windows throws a momendary dialog "Checking.... (something-or-other)..." which then disappears
without having started Bling.

Any thoughts?

**Comment by lurume84** [comment]
C:\Users\Kolon\AppData\Roaming"Bling Desktop"\bling.exe

This line lacks a \ before bling and needs to be without quotes.

I have just released a new Desktop version with a new installer that allows reinstalling without uninstalling. No longer a msi but an exe. Also moved from roaming to local folder.

On a separate note, next release will also notify of new desktop releases (hopefully). In fact, viewer is automatically downloaded and loaded by the current application. When a new viewer is available you should see a notification toast in your windows 10. I will double check if this funtionality has been lost during other modifications as another user is not having these notifications neither.
