### ISSUE TITLE
Video Download Timestamp

### ISSUE THREAD

**Issue by c4329** [lurume84/bling-desktop#9]
Hello, 

Thanks for developing this app! I installed the desktop version 0.1.6 and it is working flawlessly on my W10 desktop.  Nice job!

Only question I have regarding the app is the timestamp imbedded in the video name for the downloaded Blink videos is 5 hours latter than the actual video on my Blink cameras. Is there any parameter setting I can use to correct this?

**Comment by lurume84** [comment]
Thanks! I am working on it, will post again with new version.

**Comment by lurume84** [comment]
Version 0.1.10 now includes your request. You have to download, install it and then go to configuration file

%userprofile%\Bling.exe\Blink.ini

Edit it and add UseLocalTime=true in SyncVideo section as follows

[SyncVideo]
UseLocalTime=true

Setting this option will save videos using the computer's timezone. I could not use Blink's timezone as they do not have this information directly stored in their API but I imagine computer's timezone is OK.

I cannot put this feature as the default one as other users are already using it with the current universal time.

**Comment by c4329** [comment]
Thanks for the enhancement. I downloaded what I thought was the latest version to test the enhancement but I keep getting Desktop versioni 0.1.9.0 instead of 10. Even tried uninstall/reinstall to no avail. Any help would be appreciated. 
![Capture](https://user-images.githubusercontent.com/49692955/57051645-12c73100-6c48-11e9-85b5-abd7b8be8c19.JPG)

**Comment by c4329** [comment]
Additional info to my comment from yesterday. Version is still showing as 0.1.9.0. Not sure what changed from yesterday but the file download naming process using UserLocalTime=true is working perfectly now. I see the name is now date and timestamp which is perfect. Thanks for your help. This makes it very easy to associate the videos on the mobile app and the desktop app. Thanks again.
![Capture](https://user-images.githubusercontent.com/49692955/57079502-12657f00-6cb6-11e9-8514-167e2162557e.JPG)

**Comment by lurume84** [comment]
Yes, I forgot to update version number when I generated new release. You
already have last version. Happy to help!!
